### ISSUE TITLE
MariaDB not supported?

### ISSUE THREAD

**Issue by Gamewalker** [kibae/typeorm-auditing#1]
Hi,

I tried to use your lib with mariadb and I get the following error (without audit its working fine):

```
[Nest] 292596  - 30.08.2022, 18:36:49   ERROR [ExceptionHandler] Data type "" in "OrganizationAuditing.created_at" is not supported by "mariadb" database.
DataTypeNotSupportedError: Data type "" in "OrganizationAuditing.created_at" is not supported by "mariadb" database.
    at E:\_DEV\projekte\C4Eye\nest-backend\src\metadata-builder\EntityMetadataValidator.ts:131:27
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validate (E:\_DEV\projekte\C4Eye\nest-backend\src\metadata-builder\EntityMetadataValidator.ts:126:36)
    at E:\_DEV\projekte\C4Eye\nest-backend\src\metadata-builder\EntityMetadataValidator.ts:43:18
    at Array.forEach (<anonymous>)
    at EntityMetadataValidator.validateMany (E:\_DEV\projekte\C4Eye\nest-backend\src\metadata-builder\EntityMetadataValidator.ts:42:25)
    at DataSource.buildMetadatas (E:\_DEV\projekte\C4Eye\nest-backend\src\data-source\DataSource.ts:689:33)
    at DataSource.initialize (E:\_DEV\projekte\C4Eye\nest-backend\src\data-source\DataSource.ts:242:13)
```

```
import { AuditingAction, AuditingEntity, AuditingEntityDefaultColumns } from "typeorm-auditing";
import { Organization } from "./organization.entity";

@AuditingEntity(Organization)
export class OrganizationAuditing extends Organization implements AuditingEntityDefaultColumns {
  readonly _action: AuditingAction;
  readonly _modifiedAt: Date;
  readonly _seq: number;
}
```

```
import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn
} from "typeorm";
import User from "../../users/entities/user.entity";

@Entity()
export class Organization {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @OneToMany(() => User, user => user.organization)
  employees: User[];

  @CreateDateColumn()
  created_at?:  Date;

  @UpdateDateColumn()
  updated_at?:  Date;

  @DeleteDateColumn()
  deleted_at?:  Date;
}
```

**Comment by kibae** [comment]
@Gamewalker Thanks for reporting the problem. 🙏
I've published a new version 0.4.2 that fixes this issue, so please check it out.
If you find any other problems, please feel free to let me know.
